#!/bin/sh
# Copyright (C) 2026 Qore Technologies, s.r.o.
# SPDX-License-Identifier: MIT
set -eu
export LC_ALL=C.UTF-8
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD QORE_PGSQL_BINARY_MODULE
mkdir -p "${QORE_RPM_TEST_TMP:?set QORE_RPM_TEST_TMP}/test" "$QORE_RPM_TEST_TMP/rpm"
cp test/*.qtest "$QORE_RPM_TEST_TMP/test/"
cp rpm/with-postgres.py rpm/run-suites "$QORE_RPM_TEST_TMP/rpm/"
cd "$QORE_RPM_TEST_TMP"
exec python3 -B rpm/with-postgres.py -- rpm/run-suites test
